// Global using directives
global using Android.Content;
global using Android.Content.PM;
global using Avalonia;
global using Jab;
global using Microsoft.Extensions.Configuration;
global using Spavy.LocalStorage.Sqlite.Services;
global using Spravy.Client.Models;
global using Spravy.Core.Helpers;
global using Spravy.Domain.Extensions;
global using Spravy.Domain.Helpers;
global using Spravy.Domain.Interfaces;
global using Spravy.Domain.Models;
global using Spravy.Ui.Android.Services;
global using Spravy.Ui.Extensions;
global using Spravy.Ui.Interfaces;
global using Spravy.Ui.Modules;
global using Spravy.Ui.Services;
global using Xamarin.Essentials;
global using AndroidUri = Android.Net.Uri;
global using Cvtar = System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<Spravy.Domain.Models.Result>;
global using SpravyResult = Spravy.Domain.Models.Result;
