// Global using directives
global using System.Runtime.CompilerServices;
global using System.Text.Json.Serialization;
global using Grpc.Core;
global using Spravy.Core.Extensions;
global using Spravy.Core.Interfaces;
global using Spravy.Core.Services;
global using Spravy.Db.Errors;
global using Spravy.Db.Interfaces;
global using Spravy.Db.Sqlite.Models;
global using Spravy.Domain.Errors;
global using Spravy.Domain.Extensions;
global using Spravy.Domain.Interfaces;
global using Spravy.Domain.Models;
global using Spravy.EventBus.Db.Contexts;
global using Spravy.EventBus.Db.Sqlite.Migrator;
global using Spravy.EventBus.Db.Sqlite.Services;
global using Spravy.EventBus.Domain.Models;
global using Spravy.EventBus.Service.Services;
global using Spravy.Service.Extensions;
global using Spravy.Service.HostedServices;
global using Cvtar = System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<Spravy.Domain.Models.Result>;