// Global using directives
global using System.Runtime.CompilerServices;
global using Grpc.Core;
global using Grpc.Net.Client;
global using Jab;
global using Spravy.Authentication.Domain.Client.Models;
global using Spravy.Authentication.Domain.Client.Services;
global using Spravy.Authentication.Domain.Interfaces;
global using Spravy.Authentication.Domain.Mapper.Mappers;
global using Spravy.Authentication.Domain.Models;
global using Spravy.Authentication.Protos;
global using Spravy.Client.Enums;
global using Spravy.Client.Extensions;
global using Spravy.Client.Helpers;
global using Spravy.Client.Interfaces;
global using Spravy.Client.Models;
global using Spravy.Core.Interfaces;
global using Spravy.Domain.Extensions;
global using Spravy.Domain.Interfaces;
global using Spravy.Domain.Models;
global using Cvtar = System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<Spravy.Domain.Models.Result>;