namespace Spravy.Tests.Helpers;

public static class TextHelper
{
    public const string TextLength4 = "oymy";
    public const string TextLength3 = "oym";
    public const string TextLength51 = "oymyhvkajlvmnwkunxnexlgppszoamasapfgpwfbqktjqrqwuio";
    public const string TextLength50 = "oymyhvkajlvmnwkunxnexlgppszoamasapfgpwfbqktjqrqwui";
    public const string EmailLength51 = "oymyhvkajlvmnwkunxnexlgppszoamasapfgp@fbqktjq.qwuio";
    public const string EmailLength50 = "oymyhvkajlvmnwkunxnexlgppszoamasapfgp@fbqktjq.qwui";
    public const string Email = "straging@spravy.com.ua";
    public const string TextWithSpaceLength8 = "lmhi fnb";
    public const string TextLength8 = "lmhifnba";
    public const string TextLength7 = "udsdyjy";

    public const string TextLength512 =
        "tdzpbgkejkqabowvelceccerejximmqfhqroznwvwhsnxdzgiitjbruxjkwrcufywmyxixtjjbiqwikffdypwoebuiaicqpxrwqpomtwpobzzflrqlpnsgefxxmmdbippneuyevulyjawzhhqplfhtdwesocvdnfgnqvkerifqljotvevcwemvuucbnvstomavbnnxqwnexuhgkcdxgokcrxhoadruferxtfueyfpcdatihwszvrmayerjhjpvhqfzziszucdifwyowhouimaubmpxwsyddncvnqzddqriejjmsjxdychuibkpfcnglvbdvaellonfrkfpgxmptgigfiprbzjjngihoesomrpkjvrtqedtwjwsqqbweqlrqvdjpvljrtqsyrwinthofqmdwherykyroiyktiotkbebjewboalzzomrupvcwfivssmzvsewlzzdmrdphuwzovzdbxysmcnoldxsralccfxqoxcwywxbjxsdmatnrjzqrx";

    public const string TextWithSpaceLength512 =
        "tdzpbgkejkqabowvelceccerejximmqfhqroznwvwhsnxdzgiitjbruxjkwrcufywmyxixtjjbiqwikffdypwoebuiaicqpxrwqpomtwpobzzflrqlpnsgefxxmmdbippneuyevulyjawzhhqplfhtdwesocvdnfgnqvkerifqljotvevcwemvuucbnvstomavbnnxqwnexuhgkcdxgokcrxhoadruferxtfueyfpcdatihwszvrmayerjhjpvhqfzziszucdifwyowhouimaubmpxwsyddncvnqzddqriejjmsjxdychuibkpfcnglvbdvaellonfrkfpgxmptgigfiprbzjjngihoesomrpkjvrtqedtwjwsqqbweqlrqvdjpvljrtqsyrwinthofqmdwherykyroiyktiotkbebjewboalzzomrupvcwfivssmzvsewlzzdmrdphuwzovzdbxysmcnoldxsralccfxqoxcwywxbjxsdm tnrjzqrx";

    public const string TextLength513 =
        "tdzpbgkejkqabowvelceccerejximmqfhqroznwvwhsnxdzgiitjbruxjkwrcufywmyxixtjjbiqwikffdypwoebuiaicqpxrwqpomtwpobzzflrqlpnsgefxxmmdbippneuyevulyjawzhhqplfhtdwesocvdnfgnqvkerifqljotvevcwemvuucbnvstomavbnnxqwnexuhgkcdxgokcrxhoadruferxtfueyfpcdatihwszvrmayerjhjpvhqfzziszucdifwyowhouimaubmpxwsyddncvnqzddqriejjmsjxdychuibkpfcnglvbdvaellonfrkfpgxmptgigfiprbzjjngihoesomrpkjvrtqedtwjwsqqbweqlrqvdjpvljrtqsyrwinthofqmdwherykyroiyktiotkbebjewboalzzomrupvcwfivssmzvsewlzzdmrdphuwzovzdbxysmcnoldxsralccfxqoxcwywxbjxsdmatnrjzqrxa";
}